interface KycBasicPayload {
    full_name: string
    gender: string
    date_of_birth: string
    country_of_birth: string
    citizenship: string
    identity_card: string
    npwp?: string
    province: string
    city: string
    house_number: string
    home_fax?: string
    home_telephone?: string
    postal_code: string
    street: string
    marital_status: string
    spouse_name?: string
    mother_maiden_name: string
    account_opening_purpose: string
    investment_experience: boolean
    investment_experience_detail?: string
    futures_trading_experience: boolean
    futures_broker_name?: string
    bappebti_family_member: boolean
    name_of_bappebti_family_member: string
    have_you_ever_been_declared_bankrupt: boolean
    occupation: string
    employer_name?: string
    line_of_business?: string
    position?: string
    employment_period?: string
    previous_employment_period?: string
    office_address?: string
    office_phone_number?: string
    office_fax?: string
    annual_income: string
    house_ownership_status: string
    house_ownership_detail?: string
    property_location: string
    property_value: number
    bank_deposit: number
    other_wealth_balance: number
    bank_account_name_holder: string
    bank_id: string
    bank_name?: string
    branch_name: string
    account_number: string
    bank_phone_number: string
    account_type: string
    upload_bank_statement?: string
    emergency_contact_name: string
    emergency_contact_address: string
    emergency_contact_number: string
    emergency_contact_relationship: string
}
